"""add_sequence_to_timeline_event

Revision ID: cd2baf5b527a
Revises: 61eb15c8a2d1
Create Date: 2026-04-28 12:36:06.249827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2baf5b527a'
down_revision: Union[str, Sequence[str], None] = '61eb15c8a2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.Integer(), nullable=False))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('plan', 'file_read', 'file_write', 'command', 'test', 'preview', 'comment', 'decision', 'error', 'stage_patch', 'plan_step_status_patch', 'evidence_node_patch', 'terminal_log_append', 'checkpoint', name='timelineeventtype'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_timeline_event_sequence'), ['sequence'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_event_sequence'))
        batch_op.alter_column('type',
               existing_type=sa.Enum('plan', 'file_read', 'file_write', 'command', 'test', 'preview', 'comment', 'decision', 'error', 'stage_patch', 'plan_step_status_patch', 'evidence_node_patch', 'terminal_log_append', 'checkpoint', name='timelineeventtype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###
