/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects__get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_api_tickets__get"];
        put?: never;
        /** Create Ticket */
        post: operations["create_ticket_api_tickets__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket */
        get: operations["get_ticket_api_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Ticket */
        patch: operations["update_ticket_api_tickets__ticket_id__patch"];
        trace?: never;
    };
    "/api/tickets/{ticket_id}/timeline-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Timeline Events */
        get: operations["list_timeline_events_api_tickets__ticket_id__timeline_events_get"];
        put?: never;
        /** Create Timeline Event */
        post: operations["create_timeline_event_api_tickets__ticket_id__timeline_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptanceCheckType
         * @enum {string}
         */
        AcceptanceCheckType: "manual" | "playwright" | "dom" | "screenshot" | "console";
        /** AcceptanceCriterionRead */
        AcceptanceCriterionRead: {
            /** Ticketid */
            ticketId: string;
            /** Text */
            text: string;
            /** @default manual */
            checkType: components["schemas"]["AcceptanceCheckType"];
            /** Generatedcheck */
            generatedCheck?: string | null;
            /** @default pending */
            status: components["schemas"]["AcceptanceStatus"];
            /** Lastrunat */
            lastRunAt?: string | null;
            /** Lasterror */
            lastError?: string | null;
            /** Id */
            id: string;
        };
        /**
         * AcceptanceStatus
         * @enum {string}
         */
        AcceptanceStatus: "pending" | "passing" | "failing" | "skipped";
        /**
         * AssigneeType
         * @enum {string}
         */
        AssigneeType: "human" | "agent" | "cell";
        /** CheckpointEventEnvelope */
        CheckpointEventEnvelope: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "checkpoint";
            /** Title */
            title: string;
            payload: components["schemas"]["CheckpointPayload"];
        };
        /** CheckpointPayload */
        CheckpointPayload: {
            /** Nodeid */
            nodeId?: string | null;
            /** Planstepid */
            planStepId?: string | null;
            /** Summary */
            summary?: string | null;
            /** Details */
            details?: string | null;
            /**
             * Requirescheckpoint
             * @default true
             */
            requiresCheckpoint: boolean;
        };
        /** EvidenceNodePatchEventEnvelope */
        EvidenceNodePatchEventEnvelope: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "evidence_node_patch";
            /** Title */
            title: string;
            payload: components["schemas"]["EvidenceNodePatchPayload"];
        };
        /** EvidenceNodePatchPayload */
        EvidenceNodePatchPayload: {
            /** Nodeid */
            nodeId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "success" | "failed";
            /** Summary */
            summary?: string | null;
            /** Details */
            details?: string | null;
            /** Artifactpath */
            artifactPath?: string | null;
            /** Failurereason */
            failureReason?: string | null;
            /** Requirescheckpoint */
            requiresCheckpoint?: boolean | null;
            /** Planstepid */
            planStepId?: string | null;
            /** Evidencetype */
            evidenceType?: ("ui_preview" | "test_log" | "api_response" | "file_change" | "command" | "agent_decision" | "user_correction" | "checkpoint") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LegacyTimelineEventEnvelope */
        LegacyTimelineEventEnvelope: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "command" | "comment" | "decision" | "error" | "file_read" | "file_write" | "plan" | "preview" | "test";
            /** Title */
            title: string;
            payload?: components["schemas"]["LegacyTimelinePayload"];
        };
        /** LegacyTimelinePayload */
        LegacyTimelinePayload: {
            [key: string]: unknown;
        };
        /** PlanStepStatusPatchEventEnvelope */
        PlanStepStatusPatchEventEnvelope: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "plan_step_status_patch";
            /** Title */
            title: string;
            payload: components["schemas"]["PlanStepStatusPatchPayload"];
        };
        /** PlanStepStatusPatchPayload */
        PlanStepStatusPatchPayload: {
            /** Planstepid */
            planStepId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "success" | "failed";
            /** Summary */
            summary?: string | null;
            /** Details */
            details?: string | null;
            /** Requirescheckpoint */
            requiresCheckpoint?: boolean | null;
        };
        /**
         * PreviewStatus
         * @enum {string}
         */
        PreviewStatus: "idle" | "starting" | "running" | "failed" | "stopped";
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Repositoryurl */
            repositoryUrl?: string | null;
            /** Localpath */
            localPath?: string | null;
            /** Defaultbranch */
            defaultBranch?: string | null;
            /** Previewcommand */
            previewCommand?: string | null;
            /** Installcommand */
            installCommand?: string | null;
            /** Testcommand */
            testCommand?: string | null;
        };
        /** ProjectRead */
        ProjectRead: {
            /** Name */
            name: string;
            /** Repositoryurl */
            repositoryUrl?: string | null;
            /** Localpath */
            localPath?: string | null;
            /** Defaultbranch */
            defaultBranch?: string | null;
            /** Previewcommand */
            previewCommand?: string | null;
            /** Installcommand */
            installCommand?: string | null;
            /** Testcommand */
            testCommand?: string | null;
            /** Id */
            id: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** StagePatchEventEnvelope */
        StagePatchEventEnvelope: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "stage_patch";
            /** Title */
            title: string;
            payload: components["schemas"]["StagePatchPayload"];
        };
        /** StagePatchPayload */
        StagePatchPayload: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "brief" | "plan" | "evidence" | "review";
        };
        /** TerminalLogAppendEventEnvelope */
        TerminalLogAppendEventEnvelope: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "terminal_log_append";
            /** Title */
            title: string;
            payload: components["schemas"]["TerminalLogAppendPayload"];
        };
        /** TerminalLogAppendPayload */
        TerminalLogAppendPayload: {
            /** Nodeid */
            nodeId?: string | null;
            /** Planstepid */
            planStepId?: string | null;
            /** Tag */
            tag?: string | null;
            /** Text */
            text: string;
            /** Tagcolor */
            tagColor?: string | null;
            /** Textcolor */
            textColor?: string | null;
        };
        /** TicketCreate */
        TicketCreate: {
            /** Projectid */
            projectId: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** @default backlog */
            status: components["schemas"]["TicketStatus"];
            /** @default medium */
            priority: components["schemas"]["TicketPriority"];
            assigneeType?: components["schemas"]["AssigneeType"] | null;
            /** Assigneeid */
            assigneeId?: string | null;
            /** Branchname */
            branchName?: string | null;
            /** Previewurl */
            previewUrl?: string | null;
            /** @default idle */
            previewStatus: components["schemas"]["PreviewStatus"];
            /**
             * Acceptancescore
             * @default 0
             */
            acceptanceScore: number;
        };
        /** TicketDetailRead */
        TicketDetailRead: {
            /** Projectid */
            projectId: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** @default backlog */
            status: components["schemas"]["TicketStatus"];
            /** @default medium */
            priority: components["schemas"]["TicketPriority"];
            assigneeType?: components["schemas"]["AssigneeType"] | null;
            /** Assigneeid */
            assigneeId?: string | null;
            /** Branchname */
            branchName?: string | null;
            /** Previewurl */
            previewUrl?: string | null;
            /** @default idle */
            previewStatus: components["schemas"]["PreviewStatus"];
            /**
             * Acceptancescore
             * @default 0
             */
            acceptanceScore: number;
            /** Id */
            id: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** @default brief */
            vibeStage: components["schemas"]["VibeStage"];
            /** Acceptancecriteria */
            acceptanceCriteria?: components["schemas"]["AcceptanceCriterionRead"][];
            /** Timelineevents */
            timelineEvents?: components["schemas"]["TimelineEventRead"][];
        };
        /**
         * TicketPriority
         * @enum {string}
         */
        TicketPriority: "low" | "medium" | "high";
        /** TicketRead */
        TicketRead: {
            /** Projectid */
            projectId: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** @default backlog */
            status: components["schemas"]["TicketStatus"];
            /** @default medium */
            priority: components["schemas"]["TicketPriority"];
            assigneeType?: components["schemas"]["AssigneeType"] | null;
            /** Assigneeid */
            assigneeId?: string | null;
            /** Branchname */
            branchName?: string | null;
            /** Previewurl */
            previewUrl?: string | null;
            /** @default idle */
            previewStatus: components["schemas"]["PreviewStatus"];
            /**
             * Acceptancescore
             * @default 0
             */
            acceptanceScore: number;
            /** Id */
            id: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** @default brief */
            vibeStage: components["schemas"]["VibeStage"];
        };
        /**
         * TicketStatus
         * @enum {string}
         */
        TicketStatus: "backlog" | "ready" | "in_progress" | "review" | "done" | "blocked";
        /** TicketUpdate */
        TicketUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            status?: components["schemas"]["TicketStatus"] | null;
            priority?: components["schemas"]["TicketPriority"] | null;
            assigneeType?: components["schemas"]["AssigneeType"] | null;
            /** Assigneeid */
            assigneeId?: string | null;
            /** Branchname */
            branchName?: string | null;
            /** Previewurl */
            previewUrl?: string | null;
            previewStatus?: components["schemas"]["PreviewStatus"] | null;
            /** Acceptancescore */
            acceptanceScore?: number | null;
        };
        /** TimelineEventCreate */
        TimelineEventCreate: {
            /** Ticketid */
            ticketId: string;
            /** Agentrunid */
            agentRunId?: string | null;
            /** Event */
            event: components["schemas"]["StagePatchEventEnvelope"] | components["schemas"]["PlanStepStatusPatchEventEnvelope"] | components["schemas"]["EvidenceNodePatchEventEnvelope"] | components["schemas"]["TerminalLogAppendEventEnvelope"] | components["schemas"]["CheckpointEventEnvelope"] | components["schemas"]["LegacyTimelineEventEnvelope"];
        };
        /** TimelineEventRead */
        TimelineEventRead: {
            /** Ticketid */
            ticketId: string;
            /** Agentrunid */
            agentRunId?: string | null;
            /**
             * Sequence
             * @default 0
             */
            sequence: number;
            /** Id */
            id: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Event */
            event: components["schemas"]["StagePatchEventEnvelope"] | components["schemas"]["PlanStepStatusPatchEventEnvelope"] | components["schemas"]["EvidenceNodePatchEventEnvelope"] | components["schemas"]["TerminalLogAppendEventEnvelope"] | components["schemas"]["CheckpointEventEnvelope"] | components["schemas"]["LegacyTimelineEventEnvelope"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VibeStage
         * @enum {string}
         */
        VibeStage: "brief" | "plan" | "evidence" | "review";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_projects__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
        };
    };
    create_project_api_projects__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_api_tickets__get: {
        parameters: {
            query?: {
                projectId?: string | null;
                status?: components["schemas"]["TicketStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ticket_api_tickets__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_api_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ticket_api_tickets__ticket_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_timeline_events_api_tickets__ticket_id__timeline_events_get: {
        parameters: {
            query?: {
                since?: number | null;
            };
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_timeline_event_api_tickets__ticket_id__timeline_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimelineEventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
